name: Scanner Telegram

on:
  schedule:
    - cron: "2-59/5 * * * *"
  workflow_dispatch:

permissions:
  contents: write

jobs:
  run-scanner:
    runs-on: ubuntu-latest

    steps:
      - name: Descargar repositorio
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Configurar Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Instalar dependencias
        run: pip install -r requirements.txt

      - name: Ejecutar scanner
        env:
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
        run: python scanner_telegram.py

      - name: Guardar alertas enviadas
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"

          git add sent_alerts.json

          if git diff --cached --quiet; then
            echo "No hay cambios en sent_alerts.json"
          else
            git commit -m "Actualizar alertas enviadas"
            git pull --rebase origin main
            git push
          fi